version: '3'

services:
  app:
    build: .
    command: sh -c "sh ./wait-for-it.sh db:5432 -- echo 'db is up' && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432

