name: Docker Image CI

env:
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make build
